version: '3.8'

services:
  apisummary:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
